### PR TITLE
added sharedDir config

### PR DESCRIPTION
**Pull request by pepedocs**
What: Added a config called `sharedDir` that allows sharing of host dir to container dir. This is for the purpose of copying files to host (e.g. logs).

### CODE REVIEW

**Comment by pepedocs** [comment]
@chamalabey or Vinay can you please review?

**Comment by chamalabey** [comment]
@pepedocs we need to update the config instructions here https://github.com/pepedocs/ocm-workspace#configuration

**Comment by pepedocs** [comment]
hi @chamalabey I was thinking of leaving that for default/minimal configs and create a separate doc for all the available config. But that would be a different PR. WDYT?

**Comment by chamalabey** [comment]
Sounds good @pepedocs 
Please do not forget about the docs.

**Review by chamalabey — APPROVED** [review]
/lgtm

**Review by chamalabey — APPROVED** [review]

**Comment by pepedocs** [comment]
> Sounds good @pepedocs Please do not forget about the docs.

Thanks, I've created an issue for it - https://github.com/pepedocs/ocm-workspace/issues/34

**Pull request merged**
